"""
Classify BIRD dev questions as retrieval vs aggregate from gold SQL.

Retrieval: returns rows of values (SELECT columns / expressions, JOINs, WHERE,
           DISTINCT row projection, ORDER BY, LIMIT) without SQL aggregate
           functions over groups.

Aggregate: uses COUNT/SUM/AVG/MIN/MAX (or GROUP BY / HAVING), including inside
             subqueries.

Output is written by classify_questions.py to this package directory:
  preprocess_data/questions/question_types.json
  preprocess_data/questions/question_types.csv
"""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

QUESTIONS_DIR = Path(__file__).resolve().parent

# Strip quoted identifiers and literals before keyword scan.
_STRING_LITERAL = re.compile(r"'(?:''|[^'])*'", re.DOTALL)
_BACKTICK_IDENT = re.compile(r"`[^`]*`")
_DQ_IDENT = re.compile(r'"[^"]*"')

_AGG_FUNC = re.compile(
    r"(?<![A-Za-z0-9_])(COUNT|SUM|AVG|AVERAGE|MIN|MAX|TOTAL)\s*\(",
    re.IGNORECASE,
)
_GROUP_BY = re.compile(r"\bGROUP\s+BY\b", re.IGNORECASE)
_HAVING = re.compile(r"\bHAVING\b", re.IGNORECASE)


def _sql_for_analysis(sql: str) -> str:
    """Normalize SQL text for keyword detection."""
    text = sql.strip()
    text = _BACKTICK_IDENT.sub(" `` ", text)
    text = _DQ_IDENT.sub(' "" ', text)
    text = _STRING_LITERAL.sub(" '' ", text)
    text = re.sub(r"--[^\n]*", " ", text)
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    return text.upper()


def classify_gold_sql(gold_sql: str) -> Dict[str, Any]:
    """
    Classify a single gold SQL string.

    Returns:
        {
            "question_type": "retrieval" | "aggregate",
            "signals": list of human-readable detection reasons,
        }
    """
    text = _sql_for_analysis(gold_sql)
    signals: List[str] = []

    if _AGG_FUNC.search(text):
        m = _AGG_FUNC.search(text)
        signals.append(f"aggregate_function:{m.group(1).upper()}")
    if _GROUP_BY.search(text):
        signals.append("group_by")
    if _HAVING.search(text):
        signals.append("having")

    if signals:
        return {"question_type": "aggregate", "signals": signals}
    return {"question_type": "retrieval", "signals": ["no_aggregate_keywords"]}


def classify_question(entry: dict) -> Dict[str, Any]:
    """Classify one dev.json question record."""
    gold_sql = entry.get("SQL") or entry.get("sql") or ""
    meta = classify_gold_sql(gold_sql)
    return {
        "question_id": entry["question_id"],
        "db_id": entry["db_id"],
        "difficulty": entry.get("difficulty", ""),
        "question_type": meta["question_type"],
        "signals": meta["signals"],
        "gold_sql": gold_sql,
    }


def classify_dev_questions(questions: List[dict]) -> List[Dict[str, Any]]:
    return [classify_question(q) for q in questions]


def save_question_types(
    records: List[Dict[str, Any]],
    output_dir: Optional[Union[str, Path]] = None,
) -> tuple[Path, Path]:
    """Write question_types.json and question_types.csv under output_dir."""
    output_dir = Path(output_dir) if output_dir is not None else QUESTIONS_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "question_types.json"
    csv_path = output_dir / "question_types.csv"

    payload = {
        "version": 1,
        "description": (
            "Per-question retrieval vs aggregate classification from BIRD gold SQL. "
            "Generated by classify_questions.py."
        ),
        "counts": {
            "total": len(records),
            "retrieval": sum(1 for r in records if r["question_type"] == "retrieval"),
            "aggregate": sum(1 for r in records if r["question_type"] == "aggregate"),
        },
        "questions": records,
    }
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)

    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "question_id",
                "db_id",
                "difficulty",
                "question_type",
                "signals",
            ],
        )
        writer.writeheader()
        for r in records:
            writer.writerow(
                {
                    "question_id": r["question_id"],
                    "db_id": r["db_id"],
                    "difficulty": r["difficulty"],
                    "question_type": r["question_type"],
                    "signals": "|".join(r["signals"]),
                }
            )

    return json_path, csv_path


def load_question_types(
    questions_dir: Optional[Union[str, Path]] = None,
) -> Dict[int, Dict[str, Any]]:
    """
    Load question_types.json and return {question_id: record}.
    Raises FileNotFoundError if the file does not exist.
    """
    base = Path(questions_dir) if questions_dir is not None else QUESTIONS_DIR
    path = base / "question_types.json"
    with open(path, encoding="utf-8") as f:
        payload = json.load(f)
    return {int(q["question_id"]): q for q in payload["questions"]}
