"""
column_aliases_s1r.py

Standalone mapping file for the separate S1-randomized naming experiment track.

Design:
  - Table aliases are defined per database:
      TABLE_ALIASES_S1R[db_id][original_table] -> randomized_table_name
  - Column aliases are defined per database, per table:
      COLUMN_ALIASES_S1R[db_id][original_table][original_column] -> randomized_column_name

Mappings are stored as explicit literals for:
  - 9 BIRD databases used in the main experiment
  - 2 Spider databases used in current runs (car_1, tvshow)
"""

from __future__ import annotations

from typing import Dict, Optional


TABLE_ALIASES_S1R: Dict[str, Dict[str, str]] = {
    'california_schools': {
        'frpm': 'table_a',
        'satscores': 'table_c',
        'schools': 'table_b',
    },
    'debit_card_specializing': {
        'customers': 'table_d',
        'gasstations': 'table_b',
        'products': 'table_e',
        'transactions_1k': 'table_c',
        'yearmonth': 'table_a',
    },
    'european_football_2': {
        'Player_Attributes': 'table_c',
        'Player': 'table_f',
        'League': 'table_a',
        'Country': 'table_e',
        'Team': 'table_g',
        'Team_Attributes': 'table_d',
        'Match': 'table_b',
    },
    'financial': {
        'account': 'table_g',
        'card': 'table_h',
        'client': 'table_f',
        'disp': 'table_c',
        'district': 'table_b',
        'loan': 'table_d',
        'order': 'table_a',
        'trans': 'table_e',
    },
    'formula_1': {
        'circuits': 'table_j',
        'constructors': 'table_f',
        'drivers': 'table_h',
        'seasons': 'table_k',
        'races': 'table_e',
        'constructorResults': 'table_m',
        'constructorStandings': 'table_g',
        'driverStandings': 'table_l',
        'lapTimes': 'table_c',
        'pitStops': 'table_i',
        'qualifying': 'table_b',
        'status': 'table_d',
        'results': 'table_a',
    },
    'student_club': {
        'event': 'table_b',
        'major': 'table_h',
        'zip_code': 'table_f',
        'attendance': 'table_d',
        'budget': 'table_g',
        'expense': 'table_c',
        'income': 'table_a',
        'member': 'table_e',
    },
    'superhero': {
        'alignment': 'table_d',
        'attribute': 'table_j',
        'colour': 'table_i',
        'gender': 'table_e',
        'publisher': 'table_f',
        'race': 'table_c',
        'superhero': 'table_g',
        'hero_attribute': 'table_h',
        'superpower': 'table_b',
        'hero_power': 'table_a',
    },
    'thrombosis_prediction': {
        'Examination': 'table_b',
        'Patient': 'table_c',
        'Laboratory': 'table_a',
    },
    'toxicology': {
        'atom': 'table_c',
        'bond': 'table_b',
        'connected': 'table_a',
        'molecule': 'table_d',
    },
    'car_1': {
        'continents': 'table_e',
        'countries': 'table_a',
        'car_makers': 'table_d',
        'model_list': 'table_b',
        'car_names': 'table_f',
        'cars_data': 'table_c',
    },
    'tvshow': {
        'TV_Channel': 'table_c',
        'TV_series': 'table_a',
        'Cartoon': 'table_b',
    },
}


COLUMN_ALIASES_S1R: Dict[str, Dict[str, Dict[str, str]]] = {
    'california_schools': {
        'frpm': {
            'CDSCode': 'column_p',
            'Academic Year': 'column_aa',
            'County Code': 'column_m',
            'District Code': 'column_h',
            'School Code': 'column_b',
            'County Name': 'column_e',
            'District Name': 'column_w',
            'School Name': 'column_ac',
            'District Type': 'column_q',
            'School Type': 'column_k',
            'Educational Option Type': 'column_j',
            'NSLP Provision Status': 'column_i',
            'Charter School (Y/N)': 'column_n',
            'Charter School Number': 'column_u',
            'Charter Funding Type': 'column_t',
            'IRC': 'column_x',
            'Low Grade': 'column_ab',
            'High Grade': 'column_s',
            'Enrollment (K-12)': 'column_a',
            'Free Meal Count (K-12)': 'column_g',
            'Percent (%) Eligible Free (K-12)': 'column_o',
            'FRPM Count (K-12)': 'column_v',
            'Percent (%) Eligible FRPM (K-12)': 'column_l',
            'Enrollment (Ages 5-17)': 'column_y',
            'Free Meal Count (Ages 5-17)': 'column_c',
            'Percent (%) Eligible Free (Ages 5-17)': 'column_z',
            'FRPM Count (Ages 5-17)': 'column_f',
            'Percent (%) Eligible FRPM (Ages 5-17)': 'column_d',
            '2013-14 CALPADS Fall 1 Certification Status': 'column_r',
        },
        'satscores': {
            'cds': 'column_c',
            'rtype': 'column_g',
            'sname': 'column_i',
            'dname': 'column_d',
            'cname': 'column_f',
            'enroll12': 'column_h',
            'NumTstTakr': 'column_a',
            'AvgScrRead': 'column_e',
            'AvgScrMath': 'column_k',
            'AvgScrWrite': 'column_b',
            'NumGE1500': 'column_j',
        },
        'schools': {
            'CDSCode': 'column_y',
            'NCESDist': 'column_n',
            'NCESSchool': 'column_as',
            'StatusType': 'column_f',
            'County': 'column_u',
            'District': 'column_av',
            'School': 'column_ae',
            'Street': 'column_m',
            'StreetAbr': 'column_af',
            'City': 'column_ak',
            'Zip': 'column_i',
            'State': 'column_l',
            'MailStreet': 'column_a',
            'MailStrAbr': 'column_v',
            'MailCity': 'column_z',
            'MailZip': 'column_ag',
            'MailState': 'column_ao',
            'Phone': 'column_r',
            'Ext': 'column_c',
            'Website': 'column_aj',
            'OpenDate': 'column_aw',
            'ClosedDate': 'column_ab',
            'Charter': 'column_o',
            'CharterNum': 'column_ad',
            'FundingType': 'column_b',
            'DOC': 'column_h',
            'DOCType': 'column_d',
            'SOC': 'column_al',
            'SOCType': 'column_ai',
            'EdOpsCode': 'column_at',
            'EdOpsName': 'column_t',
            'EILCode': 'column_ar',
            'EILName': 'column_aq',
            'GSoffered': 'column_p',
            'GSserved': 'column_x',
            'Virtual': 'column_k',
            'Magnet': 'column_q',
            'Latitude': 'column_au',
            'Longitude': 'column_ah',
            'AdmFName1': 'column_an',
            'AdmLName1': 'column_g',
            'AdmEmail1': 'column_j',
            'AdmFName2': 'column_w',
            'AdmLName2': 'column_ac',
            'AdmEmail2': 'column_ap',
            'AdmFName3': 'column_s',
            'AdmLName3': 'column_e',
            'AdmEmail3': 'column_am',
            'LastUpdate': 'column_aa',
        },
    },
    'debit_card_specializing': {
        'customers': {
            'CustomerID': 'column_c',
            'Segment': 'column_a',
            'Currency': 'column_b',
        },
        'gasstations': {
            'GasStationID': 'column_a',
            'ChainID': 'column_d',
            'Country': 'column_b',
            'Segment': 'column_c',
        },
        'products': {
            'ProductID': 'column_a',
            'Description': 'column_b',
        },
        'transactions_1k': {
            'TransactionID': 'column_f',
            'Date': 'column_a',
            'Time': 'column_d',
            'CustomerID': 'column_i',
            'CardID': 'column_e',
            'GasStationID': 'column_c',
            'ProductID': 'column_h',
            'Amount': 'column_g',
            'Price': 'column_b',
        },
        'yearmonth': {
            'CustomerID': 'column_c',
            'Date': 'column_b',
            'Consumption': 'column_a',
        },
    },
    'european_football_2': {
        'Player_Attributes': {
            'id': 'column_ah',
            'player_fifa_api_id': 'column_aa',
            'player_api_id': 'column_f',
            'date': 'column_w',
            'overall_rating': 'column_an',
            'potential': 'column_c',
            'preferred_foot': 'column_l',
            'attacking_work_rate': 'column_ag',
            'defensive_work_rate': 'column_r',
            'crossing': 'column_b',
            'finishing': 'column_a',
            'heading_accuracy': 'column_g',
            'short_passing': 'column_ac',
            'volleys': 'column_s',
            'dribbling': 'column_i',
            'curve': 'column_ap',
            'free_kick_accuracy': 'column_e',
            'long_passing': 'column_q',
            'ball_control': 'column_am',
            'acceleration': 'column_j',
            'sprint_speed': 'column_x',
            'agility': 'column_ai',
            'reactions': 'column_d',
            'balance': 'column_v',
            'shot_power': 'column_aj',
            'jumping': 'column_z',
            'stamina': 'column_ae',
            'strength': 'column_n',
            'long_shots': 'column_u',
            'aggression': 'column_o',
            'interceptions': 'column_ab',
            'positioning': 'column_y',
            'vision': 'column_ad',
            'penalties': 'column_p',
            'marking': 'column_ak',
            'standing_tackle': 'column_al',
            'sliding_tackle': 'column_ao',
            'gk_diving': 'column_af',
            'gk_handling': 'column_t',
            'gk_kicking': 'column_h',
            'gk_positioning': 'column_k',
            'gk_reflexes': 'column_m',
        },
        'Player': {
            'id': 'column_d',
            'player_api_id': 'column_c',
            'player_name': 'column_f',
            'player_fifa_api_id': 'column_b',
            'birthday': 'column_g',
            'height': 'column_a',
            'weight': 'column_e',
        },
        'League': {
            'id': 'column_a',
            'country_id': 'column_b',
            'name': 'column_c',
        },
        'Country': {
            'id': 'column_b',
            'name': 'column_a',
        },
        'Team': {
            'id': 'column_c',
            'team_api_id': 'column_a',
            'team_fifa_api_id': 'column_d',
            'team_long_name': 'column_b',
            'team_short_name': 'column_e',
        },
        'Team_Attributes': {
            'id': 'column_c',
            'team_fifa_api_id': 'column_n',
            'team_api_id': 'column_f',
            'date': 'column_k',
            'buildUpPlaySpeed': 'column_m',
            'buildUpPlaySpeedClass': 'column_o',
            'buildUpPlayDribbling': 'column_q',
            'buildUpPlayDribblingClass': 'column_h',
            'buildUpPlayPassing': 'column_r',
            'buildUpPlayPassingClass': 'column_b',
            'buildUpPlayPositioningClass': 'column_j',
            'chanceCreationPassing': 'column_v',
            'chanceCreationPassingClass': 'column_t',
            'chanceCreationCrossing': 'column_i',
            'chanceCreationCrossingClass': 'column_y',
            'chanceCreationShooting': 'column_x',
            'chanceCreationShootingClass': 'column_s',
            'chanceCreationPositioningClass': 'column_e',
            'defencePressure': 'column_d',
            'defencePressureClass': 'column_p',
            'defenceAggression': 'column_u',
            'defenceAggressionClass': 'column_l',
            'defenceTeamWidth': 'column_w',
            'defenceTeamWidthClass': 'column_a',
            'defenceDefenderLineClass': 'column_g',
        },
        'Match': {
            'id': 'column_a',
            'country_id': 'column_y',
            'league_id': 'column_ba',
            'season': 'column_al',
            'stage': 'column_co',
            'date': 'column_cy',
            'match_api_id': 'column_cj',
            'home_team_api_id': 'column_ce',
            'away_team_api_id': 'column_bn',
            'home_team_goal': 'column_ac',
            'away_team_goal': 'column_cx',
            'home_player_X1': 'column_e',
            'home_player_X2': 'column_bv',
            'home_player_X3': 'column_bj',
            'home_player_X4': 'column_bz',
            'home_player_X5': 'column_z',
            'home_player_X6': 'column_bt',
            'home_player_X7': 'column_dk',
            'home_player_X8': 'column_q',
            'home_player_X9': 'column_dd',
            'home_player_X10': 'column_bi',
            'home_player_X11': 'column_cn',
            'away_player_X1': 'column_v',
            'away_player_X2': 'column_m',
            'away_player_X3': 'column_bc',
            'away_player_X4': 'column_aj',
            'away_player_X5': 'column_f',
            'away_player_X6': 'column_ad',
            'away_player_X7': 'column_bf',
            'away_player_X8': 'column_bb',
            'away_player_X9': 'column_ca',
            'away_player_X10': 'column_cv',
            'away_player_X11': 'column_bp',
            'home_player_Y1': 'column_az',
            'home_player_Y2': 'column_be',
            'home_player_Y3': 'column_j',
            'home_player_Y4': 'column_d',
            'home_player_Y5': 'column_br',
            'home_player_Y6': 'column_cg',
            'home_player_Y7': 'column_ag',
            'home_player_Y8': 'column_n',
            'home_player_Y9': 'column_av',
            'home_player_Y10': 'column_o',
            'home_player_Y11': 'column_s',
            'away_player_Y1': 'column_x',
            'away_player_Y2': 'column_ae',
            'away_player_Y3': 'column_di',
            'away_player_Y4': 'column_u',
            'away_player_Y5': 'column_cf',
            'away_player_Y6': 'column_cc',
            'away_player_Y7': 'column_bg',
            'away_player_Y8': 'column_cd',
            'away_player_Y9': 'column_cm',
            'away_player_Y10': 'column_bk',
            'away_player_Y11': 'column_ck',
            'home_player_1': 'column_bl',
            'home_player_2': 'column_dc',
            'home_player_3': 'column_g',
            'home_player_4': 'column_r',
            'home_player_5': 'column_bx',
            'home_player_6': 'column_ci',
            'home_player_7': 'column_b',
            'home_player_8': 'column_aw',
            'home_player_9': 'column_ar',
            'home_player_10': 'column_ab',
            'home_player_11': 'column_at',
            'away_player_1': 'column_ct',
            'away_player_2': 'column_cz',
            'away_player_3': 'column_cs',
            'away_player_4': 'column_dj',
            'away_player_5': 'column_ak',
            'away_player_6': 'column_h',
            'away_player_7': 'column_c',
            'away_player_8': 'column_db',
            'away_player_9': 'column_am',
            'away_player_10': 'column_dg',
            'away_player_11': 'column_k',
            'goal': 'column_t',
            'shoton': 'column_p',
            'shotoff': 'column_bd',
            'foulcommit': 'column_cu',
            'card': 'column_dh',
            'cross': 'column_bo',
            'corner': 'column_bw',
            'possession': 'column_bq',
            'B365H': 'column_de',
            'B365D': 'column_cp',
            'B365A': 'column_df',
            'BWH': 'column_da',
            'BWD': 'column_ai',
            'BWA': 'column_au',
            'IWH': 'column_an',
            'IWD': 'column_bs',
            'IWA': 'column_l',
            'LBH': 'column_i',
            'LBD': 'column_as',
            'LBA': 'column_bh',
            'PSH': 'column_ao',
            'PSD': 'column_aq',
            'PSA': 'column_ap',
            'WHH': 'column_ch',
            'WHD': 'column_af',
            'WHA': 'column_aa',
            'SJH': 'column_ax',
            'SJD': 'column_cl',
            'SJA': 'column_bm',
            'VCH': 'column_bu',
            'VCD': 'column_ay',
            'VCA': 'column_cb',
            'GBH': 'column_cr',
            'GBD': 'column_cq',
            'GBA': 'column_w',
            'BSH': 'column_by',
            'BSD': 'column_cw',
            'BSA': 'column_ah',
        },
    },
    'financial': {
        'account': {
            'account_id': 'column_c',
            'district_id': 'column_b',
            'frequency': 'column_d',
            'date': 'column_a',
        },
        'card': {
            'card_id': 'column_c',
            'disp_id': 'column_b',
            'type': 'column_d',
            'issued': 'column_a',
        },
        'client': {
            'client_id': 'column_b',
            'gender': 'column_d',
            'birth_date': 'column_c',
            'district_id': 'column_a',
        },
        'disp': {
            'disp_id': 'column_a',
            'client_id': 'column_b',
            'account_id': 'column_d',
            'type': 'column_c',
        },
        'district': {
            'district_id': 'column_l',
            'A2': 'column_e',
            'A3': 'column_d',
            'A4': 'column_o',
            'A5': 'column_h',
            'A6': 'column_b',
            'A7': 'column_a',
            'A8': 'column_m',
            'A9': 'column_i',
            'A10': 'column_c',
            'A11': 'column_f',
            'A12': 'column_g',
            'A13': 'column_n',
            'A14': 'column_k',
            'A15': 'column_j',
            'A16': 'column_p',
        },
        'loan': {
            'loan_id': 'column_b',
            'account_id': 'column_c',
            'date': 'column_a',
            'amount': 'column_g',
            'duration': 'column_e',
            'payments': 'column_f',
            'status': 'column_d',
        },
        'order': {
            'order_id': 'column_e',
            'account_id': 'column_b',
            'bank_to': 'column_f',
            'account_to': 'column_a',
            'amount': 'column_d',
            'k_symbol': 'column_c',
        },
        'trans': {
            'trans_id': 'column_a',
            'account_id': 'column_b',
            'date': 'column_h',
            'type': 'column_c',
            'operation': 'column_i',
            'amount': 'column_f',
            'balance': 'column_e',
            'k_symbol': 'column_g',
            'bank': 'column_j',
            'account': 'column_d',
        },
    },
    'formula_1': {
        'circuits': {
            'circuitId': 'column_a',
            'circuitRef': 'column_e',
            'name': 'column_c',
            'location': 'column_f',
            'country': 'column_d',
            'lat': 'column_h',
            'lng': 'column_b',
            'alt': 'column_g',
            'url': 'column_i',
        },
        'constructors': {
            'constructorId': 'column_d',
            'constructorRef': 'column_e',
            'name': 'column_a',
            'nationality': 'column_b',
            'url': 'column_c',
        },
        'drivers': {
            'driverId': 'column_d',
            'driverRef': 'column_a',
            'number': 'column_c',
            'code': 'column_g',
            'forename': 'column_i',
            'surname': 'column_h',
            'dob': 'column_b',
            'nationality': 'column_e',
            'url': 'column_f',
        },
        'seasons': {
            'year': 'column_a',
            'url': 'column_b',
        },
        'races': {
            'raceId': 'column_e',
            'year': 'column_c',
            'round': 'column_f',
            'circuitId': 'column_a',
            'name': 'column_b',
            'date': 'column_g',
            'time': 'column_h',
            'url': 'column_d',
        },
        'constructorResults': {
            'constructorResultsId': 'column_b',
            'raceId': 'column_d',
            'constructorId': 'column_c',
            'points': 'column_a',
            'status': 'column_e',
        },
        'constructorStandings': {
            'constructorStandingsId': 'column_c',
            'raceId': 'column_b',
            'constructorId': 'column_f',
            'points': 'column_g',
            'position': 'column_a',
            'positionText': 'column_d',
            'wins': 'column_e',
        },
        'driverStandings': {
            'driverStandingsId': 'column_d',
            'raceId': 'column_b',
            'driverId': 'column_g',
            'points': 'column_f',
            'position': 'column_c',
            'positionText': 'column_a',
            'wins': 'column_e',
        },
        'lapTimes': {
            'raceId': 'column_c',
            'driverId': 'column_d',
            'lap': 'column_b',
            'position': 'column_a',
            'time': 'column_f',
            'milliseconds': 'column_e',
        },
        'pitStops': {
            'raceId': 'column_f',
            'driverId': 'column_b',
            'stop': 'column_c',
            'lap': 'column_g',
            'time': 'column_a',
            'duration': 'column_e',
            'milliseconds': 'column_d',
        },
        'qualifying': {
            'qualifyId': 'column_b',
            'raceId': 'column_a',
            'driverId': 'column_g',
            'constructorId': 'column_d',
            'number': 'column_c',
            'position': 'column_f',
            'q1': 'column_e',
            'q2': 'column_h',
            'q3': 'column_i',
        },
        'status': {
            'statusId': 'column_a',
            'status': 'column_b',
        },
        'results': {
            'resultId': 'column_i',
            'raceId': 'column_a',
            'driverId': 'column_q',
            'constructorId': 'column_l',
            'number': 'column_o',
            'grid': 'column_h',
            'position': 'column_j',
            'positionText': 'column_p',
            'positionOrder': 'column_b',
            'points': 'column_c',
            'laps': 'column_d',
            'time': 'column_m',
            'milliseconds': 'column_r',
            'fastestLap': 'column_k',
            'rank': 'column_g',
            'fastestLapTime': 'column_n',
            'fastestLapSpeed': 'column_e',
            'statusId': 'column_f',
        },
    },
    'student_club': {
        'event': {
            'event_id': 'column_g',
            'event_name': 'column_e',
            'event_date': 'column_c',
            'type': 'column_f',
            'notes': 'column_a',
            'location': 'column_b',
            'status': 'column_d',
        },
        'major': {
            'major_id': 'column_b',
            'major_name': 'column_c',
            'department': 'column_a',
            'college': 'column_d',
        },
        'zip_code': {
            'zip_code': 'column_e',
            'type': 'column_f',
            'city': 'column_a',
            'county': 'column_d',
            'state': 'column_c',
            'short_state': 'column_b',
        },
        'attendance': {
            'link_to_event': 'column_b',
            'link_to_member': 'column_a',
        },
        'budget': {
            'budget_id': 'column_e',
            'category': 'column_g',
            'spent': 'column_d',
            'remaining': 'column_b',
            'amount': 'column_a',
            'event_status': 'column_c',
            'link_to_event': 'column_f',
        },
        'expense': {
            'expense_id': 'column_b',
            'expense_description': 'column_d',
            'expense_date': 'column_a',
            'cost': 'column_g',
            'approved': 'column_f',
            'link_to_member': 'column_e',
            'link_to_budget': 'column_c',
        },
        'income': {
            'income_id': 'column_e',
            'date_received': 'column_c',
            'amount': 'column_d',
            'source': 'column_b',
            'notes': 'column_a',
            'link_to_member': 'column_f',
        },
        'member': {
            'member_id': 'column_h',
            'first_name': 'column_a',
            'last_name': 'column_b',
            'email': 'column_f',
            'position': 'column_c',
            't_shirt_size': 'column_g',
            'phone': 'column_d',
            'zip': 'column_e',
            'link_to_major': 'column_i',
        },
    },
    'superhero': {
        'alignment': {
            'id': 'column_a',
            'alignment': 'column_b',
        },
        'attribute': {
            'id': 'column_b',
            'attribute_name': 'column_a',
        },
        'colour': {
            'id': 'column_b',
            'colour': 'column_a',
        },
        'gender': {
            'id': 'column_a',
            'gender': 'column_b',
        },
        'publisher': {
            'id': 'column_b',
            'publisher_name': 'column_a',
        },
        'race': {
            'id': 'column_a',
            'race': 'column_b',
        },
        'superhero': {
            'id': 'column_j',
            'superhero_name': 'column_i',
            'full_name': 'column_k',
            'gender_id': 'column_a',
            'eye_colour_id': 'column_e',
            'hair_colour_id': 'column_g',
            'skin_colour_id': 'column_d',
            'race_id': 'column_b',
            'publisher_id': 'column_c',
            'alignment_id': 'column_h',
            'height_cm': 'column_l',
            'weight_kg': 'column_f',
        },
        'hero_attribute': {
            'hero_id': 'column_a',
            'attribute_id': 'column_c',
            'attribute_value': 'column_b',
        },
        'superpower': {
            'id': 'column_b',
            'power_name': 'column_a',
        },
        'hero_power': {
            'hero_id': 'column_a',
            'power_id': 'column_b',
        },
    },
    'thrombosis_prediction': {
        'Examination': {
            'ID': 'column_e',
            'Examination Date': 'column_c',
            'aCL IgG': 'column_m',
            'aCL IgM': 'column_d',
            'ANA': 'column_i',
            'ANA Pattern': 'column_g',
            'aCL IgA': 'column_f',
            'Diagnosis': 'column_j',
            'KCT': 'column_b',
            'RVVT': 'column_k',
            'LAC': 'column_l',
            'Symptoms': 'column_h',
            'Thrombosis': 'column_a',
        },
        'Patient': {
            'ID': 'column_b',
            'SEX': 'column_a',
            'Birthday': 'column_d',
            'Description': 'column_c',
            'First Date': 'column_e',
            'Admission': 'column_g',
            'Diagnosis': 'column_f',
        },
        'Laboratory': {
            'ID': 'column_e',
            'Date': 'column_q',
            'GOT': 'column_f',
            'GPT': 'column_ac',
            'LDH': 'column_k',
            'ALP': 'column_h',
            'TP': 'column_af',
            'ALB': 'column_g',
            'UA': 'column_y',
            'UN': 'column_r',
            'CRE': 'column_d',
            'T-BIL': 'column_p',
            'T-CHO': 'column_al',
            'TG': 'column_z',
            'CPK': 'column_l',
            'GLU': 'column_an',
            'WBC': 'column_ar',
            'RBC': 'column_n',
            'HGB': 'column_ai',
            'HCT': 'column_ao',
            'PLT': 'column_t',
            'PT': 'column_ap',
            'APTT': 'column_ak',
            'FG': 'column_m',
            'PIC': 'column_ab',
            'TAT': 'column_ad',
            'TAT2': 'column_u',
            'U-PRO': 'column_o',
            'IGG': 'column_w',
            'IGA': 'column_am',
            'IGM': 'column_i',
            'CRP': 'column_s',
            'RA': 'column_c',
            'RF': 'column_x',
            'C3': 'column_aj',
            'C4': 'column_ag',
            'RNP': 'column_aq',
            'SM': 'column_aa',
            'SC170': 'column_a',
            'SSA': 'column_ah',
            'SSB': 'column_v',
            'CENTROMEA': 'column_ae',
            'DNA': 'column_j',
            'DNA-II': 'column_b',
        },
    },
    'toxicology': {
        'atom': {
            'atom_id': 'column_c',
            'molecule_id': 'column_a',
            'element': 'column_b',
        },
        'bond': {
            'bond_id': 'column_b',
            'molecule_id': 'column_c',
            'bond_type': 'column_a',
        },
        'connected': {
            'atom_id': 'column_a',
            'atom_id2': 'column_c',
            'bond_id': 'column_b',
        },
        'molecule': {
            'molecule_id': 'column_b',
            'label': 'column_a',
        },
    },
    'car_1': {
        'continents': {
            'ContId': 'column_b',
            'Continent': 'column_a',
        },
        'countries': {
            'CountryId': 'column_b',
            'CountryName': 'column_c',
            'Continent': 'column_a',
        },
        'car_makers': {
            'Id': 'column_b',
            'Maker': 'column_d',
            'FullName': 'column_a',
            'Country': 'column_c',
        },
        'model_list': {
            'ModelId': 'column_b',
            'Maker': 'column_a',
            'Model': 'column_c',
        },
        'car_names': {
            'MakeId': 'column_b',
            'Model': 'column_a',
            'Make': 'column_c',
        },
        'cars_data': {
            'Id': 'column_c',
            'MPG': 'column_d',
            'Cylinders': 'column_f',
            'Edispl': 'column_g',
            'Horsepower': 'column_b',
            'Weight': 'column_a',
            'Accelerate': 'column_h',
            'Year': 'column_e',
        },
    },
    'tvshow': {
        'TV_Channel': {
            'id': 'column_i',
            'series_name': 'column_f',
            'Country': 'column_d',
            'Language': 'column_b',
            'Content': 'column_a',
            'Pixel_aspect_ratio_PAR': 'column_h',
            'Hight_definition_TV': 'column_c',
            'Pay_per_view_PPV': 'column_g',
            'Package_Option': 'column_e',
        },
        'TV_series': {
            'id': 'column_c',
            'Episode': 'column_i',
            'Air_Date': 'column_e',
            'Rating': 'column_f',
            'Share': 'column_g',
            '18_49_Rating_Share': 'column_d',
            'Viewers_m': 'column_b',
            'Weekly_Rank': 'column_a',
            'Channel': 'column_h',
        },
        'Cartoon': {
            'id': 'column_a',
            'Title': 'column_b',
            'Directed_by': 'column_e',
            'Written_by': 'column_c',
            'Original_air_date': 'column_f',
            'Production_code': 'column_d',
            'Channel': 'column_g',
        },
    },
}


def get_table_name_s1r(db_id: str, original_table: str) -> str:
    """Return randomized S1R table alias (or original fallback)."""
    return TABLE_ALIASES_S1R.get(db_id, {}).get(original_table, original_table)


def get_column_name_s1r(db_id: str, original_table: str, original_column: str) -> str:
    """Return randomized S1R column alias (or original fallback)."""
    return (
        COLUMN_ALIASES_S1R.get(db_id, {})
        .get(original_table, {})
        .get(original_column, original_column)
    )


def has_s1r_db(db_id: str) -> bool:
    """True when any S1R mapping exists for the given database."""
    return db_id in TABLE_ALIASES_S1R or db_id in COLUMN_ALIASES_S1R


def get_s1r_table_aliases(db_id: str) -> Dict[str, str]:
    """Return all S1R table aliases for one database (empty dict if none)."""
    return TABLE_ALIASES_S1R.get(db_id, {})


def get_s1r_column_aliases(db_id: str, table_name: Optional[str] = None):
    """
    Return S1R column aliases for one database.

    Args:
        db_id: Database id.
        table_name: When provided, returns aliases for one table only.

    Returns:
        - If table_name is None: Dict[str, Dict[str, str]]
        - Else: Dict[str, str]
    """
    db_map = COLUMN_ALIASES_S1R.get(db_id, {})
    if table_name is None:
        return db_map
    return db_map.get(table_name, {})
