"""
evaluator.py

Evaluates predicted SQL queries using BIRD's execution accuracy metric.

Execution accuracy: execute both the predicted SQL and the gold SQL against
the real database, then compare their result sets as multisets (order-independent,
duplicate-aware). A prediction is correct if and only if the two result sets
are identical.

Three possible outcomes per question:
  - "correct"      : predicted SQL executes and result set matches gold
  - "wrong_answer" : predicted SQL executes but result set differs from gold
  - "error"        : predicted SQL fails to execute (syntax/schema error)

Semantic-level handling
-----------------------
For any condition where the schema shown to the LLM uses column names that
differ from the names in the physical SQLite file, the LLM's SQL will use
the *mapped* names and fail against the original database.  This happens:

  - At S1 always (col_a, col_b … never exist in the real file).
  - At S2/S3/S4 for databases whose original names differ from the curated
    aliases — e.g. california_schools at S3 maps "cds" → "school_cds_code",
    so the LLM writes "school_cds_code" which is not a real column.
  - The only time no mapping is needed is when *all* curated names happen to
    equal the originals (e.g. toxicology at S3 returns None from
    build_col_rename_map).

To handle this, pass a `col_rename_map` to `evaluate()`.  The evaluator will:
  1. Run the gold SQL against the original database (original column names).
  2. Run the predicted SQL against the same database file but with TEMP VIEWs
     that shadow each table and expose the *mapped* column names.
  3. Compare the two result sets by value (column names are irrelevant).

L1 / 1NF wide-table handling
----------------------------
For structural level L1, pass ``l1_view_ddls`` (from ``to_1nf.view_ddls(build_plan(...))``).
The evaluator creates those ``CREATE TEMP VIEW`` statements on the prediction
connection so predicted SQL can query ``one_nf_0`` (etc.); gold SQL still runs
on the original 3NF schema.  Pass ``col_rename_map=None`` for L1 when wide
views already expose semantic column names.

Build the map with:
    from src.evaluator import build_col_rename_map
    col_rename_map = build_col_rename_map(db_id, data_dir, semantic_level)
    # Returns None when no renaming is needed (all names already match).

Usage:
    from src.evaluator import evaluate, EvalResult, build_col_rename_map
    col_rename_map = build_col_rename_map("california_schools", "dev_20240627", 3)
    result = evaluate(db_path, predicted_sql, gold_sql, col_rename_map)
    result = evaluate(db_path, predicted_sql, gold_sql, None, l1_view_ddls)
    conn = open_l1_eval_connection(db_path, l1_view_ddls)
    try:
        result = evaluate(db_path, predicted_sql, gold_sql, None, None, conn)
    finally:
        conn.close()
    print(result.outcome)   # "correct" / "wrong_answer" / "error"
    print(result.correct)   # True / False
"""

import json
import sqlite3
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple


@dataclass
class EvalResult:
    """Holds the outcome of evaluating one predicted SQL query."""
    outcome: str            # "correct" | "wrong_answer" | "error"
    correct: bool           # True only when outcome == "correct"
    predicted_sql: str      # the SQL string that was evaluated
    gold_sql: str           # the reference SQL string
    error_msg: Optional[str] = None   # populated when outcome == "error"


def evaluate(
    db_path: str,
    predicted_sql: str,
    gold_sql: str,
    col_rename_map: Optional[Dict[str, List[Tuple[str, str]]]] = None,
    l1_view_ddls: Optional[List[str]] = None,
    l1_reuse_connection: Optional[sqlite3.Connection] = None,
    verbose: bool = False,
) -> EvalResult:
    """
    Compare predicted SQL against gold SQL by executing both on the database
    and comparing result sets.

    Args:
        db_path       : Absolute path to the SQLite database file.
        predicted_sql : SQL string generated by the LLM.
        gold_sql      : Reference SQL string from the BIRD dataset.
        col_rename_map: Optional {table: [(original_col, mapped_col), ...]}.
                        When provided, the predicted SQL is executed against
                        an in-memory view-backed DB using the *mapped* names.
                        The gold SQL always runs against the original DB.
                        Pass None for S3 (original names, no mapping needed).
        l1_view_ddls: Optional list of CREATE TEMP VIEW … statements (L1 wide
                        clusters).  Executed on the prediction connection before
                        predicted SQL.  Pass None for L3–L6.  Do not combine with
                        col_rename_map unless you know predicted SQL needs both.
        l1_reuse_connection: If set, run predicted SQL on this connection and
                        **do not** run ``l1_view_ddls`` or close it.  Use after
                        ``open_l1_eval_connection`` so L1 VIEWs are built **once**
                        per database instead of on every question (large joins
                        otherwise look “stuck”).  Pass ``l1_view_ddls=None`` when
                        using reuse.

        verbose: If True, print short progress lines around gold vs predicted
                 execution (helps locate stalls: LLM vs gold SQL vs pred SQL).

    Returns:
        EvalResult with outcome, correctness flag, and optional error message.
    """
    if not predicted_sql or not predicted_sql.strip():
        return EvalResult(
            outcome="error",
            correct=False,
            predicted_sql=predicted_sql,
            gold_sql=gold_sql,
            error_msg="Empty prediction — LLM returned no SQL.",
        )

    # Gold SQL always executes against the original physical database
    orig_conn = sqlite3.connect(db_path)
    orig_conn.text_factory = str
    if verbose:
        print("  [eval] running gold SQL…", flush=True)
    try:
        gold_rows = _execute(orig_conn, gold_sql)
    finally:
        orig_conn.close()
    if verbose:
        print(f"  [eval] gold finished ({len(gold_rows)} rows)", flush=True)

    # Predicted SQL executes against either:
    #   (a) the original DB (no rename map, no L1 views),
    #   (b) original DB + L1 TEMP VIEWs (wide clusters),
    #   (c) original DB + TEMP VIEWs shadowing base tables with mapped names.
    if l1_reuse_connection is not None:
        pred_conn = l1_reuse_connection
        close_pred = False
    elif l1_view_ddls or col_rename_map:
        pred_conn = _build_pred_connection(db_path, col_rename_map, l1_view_ddls)
        close_pred = True
    else:
        pred_conn = sqlite3.connect(db_path)
        pred_conn.text_factory = str
        close_pred = True

    if verbose:
        print("  [eval] running predicted SQL…", flush=True)
    try:
        pred_rows, error_msg = _execute_safe(pred_conn, predicted_sql)
    finally:
        if close_pred:
            pred_conn.close()
    if verbose:
        if error_msg:
            print(f"  [eval] predicted SQL failed: {error_msg[:300]}", flush=True)
        else:
            print(f"  [eval] predicted finished ({len(pred_rows)} rows)", flush=True)

    if error_msg is not None:
        return EvalResult(
            outcome="error",
            correct=False,
            predicted_sql=predicted_sql,
            gold_sql=gold_sql,
            error_msg=error_msg,
        )

    # Compare result sets as multisets — order does not matter, duplicates do
    if _result_sets_equal(pred_rows, gold_rows):
        return EvalResult(
            outcome="correct",
            correct=True,
            predicted_sql=predicted_sql,
            gold_sql=gold_sql,
        )
    else:
        return EvalResult(
            outcome="wrong_answer",
            correct=False,
            predicted_sql=predicted_sql,
            gold_sql=gold_sql,
        )


def execution_accuracy(results: list) -> float:
    """
    Compute overall execution accuracy from a list of EvalResult objects.

    Args:
        results: List of EvalResult instances.

    Returns:
        Fraction of correct predictions (0.0 – 1.0).
    """
    if not results:
        return 0.0
    return sum(1 for r in results if r.correct) / len(results)


def accuracy_by_difficulty(results: list, difficulties: list) -> dict:
    """
    Compute execution accuracy broken down by BIRD difficulty tier.

    Args:
        results     : List of EvalResult instances.
        difficulties: List of difficulty strings matching results by index
                      (e.g. ['simple', 'moderate', 'challenging']).

    Returns:
        Dict mapping difficulty tier to accuracy, e.g.:
        {'simple': 0.82, 'moderate': 0.61, 'challenging': 0.44, 'overall': 0.65}
    """
    from collections import defaultdict
    tier_correct = defaultdict(int)
    tier_total = defaultdict(int)

    for result, diff in zip(results, difficulties):
        tier_total[diff] += 1
        if result.correct:
            tier_correct[diff] += 1

    breakdown = {
        tier: tier_correct[tier] / tier_total[tier]
        for tier in tier_total
    }
    breakdown["overall"] = execution_accuracy(results)
    return breakdown


# ---------------------------------------------------------------------------
# Column-rename map builder (public helper)
# ---------------------------------------------------------------------------

def build_col_rename_map(
    db_id: str,
    data_dir: str,
    semantic_level: int,
) -> Optional[Dict[str, List[Tuple[str, str]]]]:
    """
    Build a {table: [(original_col, mapped_col), ...]} mapping for the given
    database and semantic level.

    Returns None when semantic_level == 3 AND all mapped names equal the
    original names (no views are needed).  For S1/S2/S4 and any database
    where names differ, returns the full mapping.

    The caller passes this to evaluate() so the evaluator knows how to
    translate the LLM's SQL back to real column names.
    """
    from src.column_aliases import get_name as _alias

    tables_path = Path(data_dir) / "dev_tables.json"
    with open(tables_path, encoding="utf-8") as f:
        all_entries = json.load(f)
    entry = next(t for t in all_entries if t["db_id"] == db_id)

    table_names = entry["table_names_original"]
    col_names_original = entry["column_names_original"]  # [(table_idx, col_name), ...]

    # Group original column names by table (in order)
    cols_by_table: Dict[str, List[str]] = {t: [] for t in table_names}
    for table_idx, col_name in col_names_original:
        if table_idx == -1:
            continue
        cols_by_table[table_names[table_idx]].append(col_name)

    rename_map: Dict[str, List[Tuple[str, str]]] = {}
    any_changed = False

    for table, orig_cols in cols_by_table.items():
        pairs: List[Tuple[str, str]] = []
        for col_pos, orig in enumerate(orig_cols):
            if semantic_level == 1:
                # positional: col_a, col_b, …
                from src.schema_builder import _idx_to_label
                mapped = f"col_{_idx_to_label(col_pos)}"
            else:
                mapped = _alias(db_id, orig, semantic_level)

            pairs.append((orig, mapped))
            if mapped != orig:
                any_changed = True
        rename_map[table] = pairs

    # If nothing changed (all names identical), no views needed → return None
    return rename_map if any_changed else None


# ---------------------------------------------------------------------------
# Prediction-connection helpers (L1 reuse)
# ---------------------------------------------------------------------------


def open_l1_eval_connection(db_path: str, l1_view_ddls: List[str]) -> sqlite3.Connection:
    """
    Open the SQLite file and install L1 wide-cluster TEMP VIEWs once.

    Reuse this connection across many ``evaluate(..., l1_reuse_connection=conn)``
    calls for the same database to avoid rebuilding huge JOIN views every time.
    The caller must ``close()`` the connection when finished.
    """
    return _build_pred_connection(db_path, None, l1_view_ddls)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _build_pred_connection(
    db_path: str,
    col_rename_map: Optional[Dict[str, List[Tuple[str, str]]]],
    l1_view_ddls: Optional[List[str]],
) -> sqlite3.Connection:
    """
    Open the physical SQLite DB and optionally install:
      1) L1 wide-cluster TEMP VIEWs (read from main.*),
      2) TEMP VIEWs that shadow base tables with mapped column names.
    """
    conn = sqlite3.connect(db_path)
    conn.text_factory = str
    if l1_view_ddls:
        for ddl in l1_view_ddls:
            try:
                conn.execute(ddl)
            except sqlite3.OperationalError as e:
                print(f"[evaluator] Warning: L1 VIEW DDL failed: {e}")
    if col_rename_map:
        for table, pairs in col_rename_map.items():
            select_parts = [
                f'main."{table}"."{orig_col}" AS `{mapped_col}`'
                for orig_col, mapped_col in pairs
            ]
            view_sql = (
                f'CREATE TEMP VIEW "{table}" AS '
                f'SELECT {", ".join(select_parts)} '
                f'FROM main."{table}"'
            )
            try:
                conn.execute(view_sql)
            except sqlite3.OperationalError as e:
                print(f"[evaluator] Warning: could not create TEMP VIEW for '{table}': {e}")
    return conn


def _build_view_conn(
    db_path: str,
    col_rename_map: Dict[str, List[Tuple[str, str]]],
) -> sqlite3.Connection:
    """Backward-compatible wrapper: rename-map views only."""
    return _build_pred_connection(db_path, col_rename_map, None)


def _execute(conn: sqlite3.Connection, sql: str) -> list:
    """Execute SQL and return all rows. Raises on error."""
    cursor = conn.execute(sql)
    return cursor.fetchall()


def _execute_safe(conn: sqlite3.Connection, sql: str):
    """
    Execute SQL without raising. Returns (rows, None) on success,
    (None, error_message) on failure.
    """
    try:
        rows = _execute(conn, sql)
        return rows, None
    except Exception as e:
        return None, str(e)


def _result_sets_equal(pred_rows: list, gold_rows: list) -> bool:
    """
    Compare two result sets as multisets (Counter over normalised rows).
    Normalisation converts each value to a comparable string to avoid
    type mismatches between INTEGER 1 and REAL 1.0 representing the same value.
    """
    return Counter(_normalise(pred_rows)) == Counter(_normalise(gold_rows))


def _normalise(rows: list) -> list:
    """
    Convert each row to a tuple of normalised string values so that
    equivalent values with different Python types compare as equal.

    Examples:
      (1,)   and (1.0,)  → both become ('1',)    → equal
      (None,)            → ('',)
      ('YES',)           → ('yes',)               → case-insensitive
    """
    normalised = []
    for row in rows:
        norm_row = tuple(
            "" if v is None
            else str(float(v)).rstrip("0").rstrip(".") if _is_numeric(v)
            else str(v).strip().lower()
            for v in row
        )
        normalised.append(norm_row)
    return normalised


def _is_numeric(value) -> bool:
    """Return True if value is an int or float (not a string)."""
    return isinstance(value, (int, float)) and not isinstance(value, bool)
