"""
evaluator.py

Evaluates predicted SQL queries using BIRD's execution accuracy metric.

Execution accuracy: execute both the predicted SQL and the gold SQL against
the real database, then compare their result sets as multisets (order-independent,
duplicate-aware). A prediction is correct if and only if the two result sets
are identical.

Three possible outcomes per question:
  - "correct"      : predicted SQL executes and result set matches gold
  - "wrong_answer" : predicted SQL executes but result set differs from gold
  - "error"        : predicted SQL fails to execute (syntax/schema error)

Semantic-level handling
-----------------------
For any condition where the schema shown to the LLM uses column names that
differ from the names in the physical SQLite file, the LLM's SQL will use
the *mapped* names and fail against the original database.  This happens:

  - At S1 always (col_a, col_b … never exist in the real file).
  - At S2/S3/S4 for databases whose original names differ from the curated
    aliases — e.g. california_schools at S3 maps "cds" → "school_cds_code",
    so the LLM writes "school_cds_code" which is not a real column.
  - The only time no mapping is needed is when *all* curated names happen to
    equal the originals (e.g. toxicology at S3 returns None from
    build_col_rename_map).

To handle this, pass a `col_rename_map` to `evaluate()`.  The evaluator will:
  1. Run the gold SQL against the original database (original column names).
  2. Run the predicted SQL against the same database file but with TEMP VIEWs
     that shadow each table and expose the *mapped* column names.
  3. Compare the two result sets by value (column names are irrelevant).

L1 / L2 materialised wide-table handling
----------------------------------------
For L1, pass ``predicted_db_path`` to ``{db_id}__1nf.sqlite`` (see
``SchemaBuilder.one_nf_sqlite_path``).  For L2, use ``{db_id}__2nf.sqlite`` (see
``SchemaBuilder.two_nf_sqlite_path``).  Predicted SQL runs on that file; gold SQL
still runs on the original 3NF database.  Result comparison is always **multiset**
(BIRD execution accuracy).  L1/L2 prompts instruct the model to use DISTINCT /
COUNT(DISTINCT …) / deduplicating subqueries on denormalised tables.

Use ``build_l1_col_rename_map`` / ``build_l2_col_rename_map`` for S1/S2/S4 on L1/L2.

Build the map with:
    from src.evaluator import build_col_rename_map
    col_rename_map = build_col_rename_map(db_id, data_dir, semantic_level)
    # Returns None when no renaming is needed (all names already match).

Usage:
    from src.evaluator import evaluate, EvalResult, build_col_rename_map
    col_rename_map = build_col_rename_map("california_schools", "dev_20240627", 3)
    result = evaluate(db_path, predicted_sql, gold_sql, col_rename_map)
    result = evaluate(
        db_path, predicted_sql, gold_sql,
        predicted_db_path=str(SchemaBuilder.one_nf_sqlite_path(data_dir, db_id)),
    )
    print(result.outcome)   # "correct" / "wrong_answer" / "error"
    print(result.correct)   # True / False
"""

import json
import sqlite3
import time
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Abort SQL that runs longer than this (seconds). Prevents experiment hangs on
# pathological LLM queries (cartesian joins, missing predicates, etc.).
_SQL_TIMEOUT_SEC = 120


@dataclass
class EvalResult:
    """Holds the outcome of evaluating one predicted SQL query."""
    outcome: str            # "correct" | "wrong_answer" | "error"
    correct: bool           # True only when outcome == "correct"
    predicted_sql: str      # the SQL string that was evaluated
    gold_sql: str           # the reference SQL string
    error_msg: Optional[str] = None   # populated when outcome == "error"
    eval_method: Optional[str] = None  # "multiset"


def evaluate(
    db_path: str,
    predicted_sql: str,
    gold_sql: str,
    col_rename_map: Optional[Dict[str, List[Tuple[str, str]]]] = None,
    predicted_db_path: Optional[str] = None,
    pred_reuse_connection: Optional[sqlite3.Connection] = None,
    verbose: bool = False,
) -> EvalResult:
    """
    Compare predicted SQL against gold SQL by executing both on the database
    and comparing result sets.

    Args:
        db_path       : Absolute path to the SQLite database file.
        predicted_sql : SQL string generated by the LLM.
        gold_sql      : Reference SQL string from the BIRD dataset.
        col_rename_map: Optional {table: [(original_col, mapped_col), ...]}.
                        When provided, TEMP VIEWs expose *mapped* column names to
                        the predicted SQL.  Works on the 3NF DB (L3–L6) or on
                        ``predicted_db_path`` (L1/L2 materialised DB).  Pass None when
                        predicted column names match physical names (L3 S3, L1/L2 S3).
        predicted_db_path: Optional path to a materialised L1 or L2 SQLite file.
                        Predicted SQL runs on this file; gold SQL on ``db_path``.
                        Combine with ``col_rename_map`` for L1/L2 S1/S2/S4.
        pred_reuse_connection: Reuse an open connection to ``predicted_db_path``
                        (caller must close).  Pass ``predicted_db_path=None`` when
                        using reuse.

        verbose: If True, print short progress lines around gold vs predicted
                 execution (helps locate stalls: LLM vs gold SQL vs pred SQL).

    Returns:
        EvalResult with outcome, correctness flag, and optional error message.
    """
    if not predicted_sql or not predicted_sql.strip():
        return EvalResult(
            outcome="error",
            correct=False,
            predicted_sql=predicted_sql,
            gold_sql=gold_sql,
            error_msg="Empty prediction — LLM returned no SQL.",
        )

    # Gold SQL always executes against the original physical database
    orig_conn = sqlite3.connect(db_path)
    orig_conn.text_factory = str
    if verbose:
        print("  [eval] running gold SQL…", flush=True)
    try:
        gold_rows = _execute(orig_conn, gold_sql)
    finally:
        orig_conn.close()
    if verbose:
        print(f"  [eval] gold finished ({len(gold_rows)} rows)", flush=True)

    # Predicted SQL executes against either:
    #   (a) the materialised L1/L2 file,
    #   (b) the original DB + TEMP VIEWs with mapped column names (L3–L6, S≠original),
    #   (c) the original DB as-is.
    if pred_reuse_connection is not None:
        pred_conn = pred_reuse_connection
        close_pred = False
    elif predicted_db_path:
        pred_conn = _build_pred_connection(
            predicted_db_path, col_rename_map or {}
        )
        close_pred = True
    elif col_rename_map:
        pred_conn = _build_pred_connection(db_path, col_rename_map)
        close_pred = True
    else:
        pred_conn = sqlite3.connect(db_path)
        pred_conn.text_factory = str
        close_pred = True

    if verbose:
        print("  [eval] running predicted SQL…", flush=True)
    try:
        pred_rows, error_msg = _execute_safe(pred_conn, predicted_sql)
        if verbose:
            if error_msg:
                print(f"  [eval] predicted SQL failed: {error_msg[:300]}", flush=True)
            else:
                print(f"  [eval] predicted finished ({len(pred_rows)} rows)", flush=True)

        if error_msg is not None:
            return EvalResult(
                outcome="error",
                correct=False,
                predicted_sql=predicted_sql,
                gold_sql=gold_sql,
                error_msg=error_msg,
            )

        if _result_sets_equal(pred_rows, gold_rows):
            return EvalResult(
                outcome="correct",
                correct=True,
                predicted_sql=predicted_sql,
                gold_sql=gold_sql,
                eval_method="multiset",
            )

        return EvalResult(
            outcome="wrong_answer",
            correct=False,
            predicted_sql=predicted_sql,
            gold_sql=gold_sql,
            eval_method="multiset",
        )
    finally:
        if close_pred:
            pred_conn.close()


# ---------------------------------------------------------------------------
# Column-rename map builder (public helper)
# ---------------------------------------------------------------------------

def build_col_rename_map(
    db_id: str,
    data_dir: str,
    semantic_level: int,
) -> Optional[Dict[str, List[Tuple[str, str]]]]:
    """
    Build a {table: [(original_col, mapped_col), ...]} mapping for the given
    database and semantic level.

    Returns None when semantic_level == 3 AND all mapped names equal the
    original names (no views are needed).  For S1/S2/S4 and any database
    where names differ, returns the full mapping.

    The caller passes this to evaluate() so the evaluator knows how to
    translate the LLM's SQL back to real column names.
    """
    from src.column_aliases import get_name as _alias

    tables_path = Path(data_dir) / "dev_tables.json"
    with open(tables_path, encoding="utf-8") as f:
        all_entries = json.load(f)
    entry = next(t for t in all_entries if t["db_id"] == db_id)

    table_names = entry["table_names_original"]
    col_names_original = entry["column_names_original"]  # [(table_idx, col_name), ...]

    # Group original column names by table (in order)
    cols_by_table: Dict[str, List[str]] = {t: [] for t in table_names}
    for table_idx, col_name in col_names_original:
        if table_idx == -1:
            continue
        cols_by_table[table_names[table_idx]].append(col_name)

    rename_map: Dict[str, List[Tuple[str, str]]] = {}
    any_changed = False

    for table, orig_cols in cols_by_table.items():
        pairs: List[Tuple[str, str]] = []
        for col_pos, orig in enumerate(orig_cols):
            if semantic_level == 1:
                # positional: col_a, col_b, …
                from src.schema_builder import _idx_to_label
                mapped = f"col_{_idx_to_label(col_pos)}"
            else:
                mapped = _alias(db_id, orig, semantic_level)

            pairs.append((orig, mapped))
            if mapped != orig:
                any_changed = True
        rename_map[table] = pairs

    # If nothing changed (all names identical), no views needed → return None
    return rename_map if any_changed else None


def build_l1_col_rename_map(
    db_id: str,
    data_dir: str,
    semantic_level: int,
) -> Optional[Dict[str, List[Tuple[str, str]]]]:
    """
    Column rename map for L1: physical names in ``{db_id}__1nf.sqlite`` (S3-style)
    → display names shown in the prompt at *semantic_level*.

    Same idea as ``build_col_rename_map`` for L3–L6, but for the single wide table
    ``one_nf_0``.
    """
    from preprocess_data.to_1nf.convert import build_plan
    from src.schema_builder import L1_TABLE_NAME

    phys = build_plan(db_id, data_dir, semantic_level=3).display_columns
    disp = build_plan(db_id, data_dir, semantic_level=semantic_level).display_columns
    if phys == disp:
        return None
    return {L1_TABLE_NAME: list(zip(phys, disp))}


def build_l2_col_rename_map(
    db_id: str,
    data_dir: str,
    semantic_level: int,
) -> Optional[Dict[str, List[Tuple[str, str]]]]:
    """
    Column rename map for L2: physical names in ``{db_id}__2nf.sqlite`` (built at S3)
    → display names shown in the prompt at *semantic_level*, per cluster table.

    Returns None when every cluster uses identical physical and display names (S3).
    """
    from preprocess_data.to_2nf.convert import build_plan
    from preprocess_data.to_2nf.specs import SPECS

    if db_id not in SPECS:
        return None

    plan_phys = build_plan(db_id, data_dir, semantic_level=3)
    plan_disp = build_plan(db_id, data_dir, semantic_level=semantic_level)

    if len(plan_phys.clusters) != len(plan_disp.clusters):
        raise ValueError(f"2NF plan cluster count mismatch for db_id={db_id!r}")

    rename_map: Dict[str, List[Tuple[str, str]]] = {}
    any_changed = False
    for p_phys, p_disp in zip(plan_phys.clusters, plan_disp.clusters):
        if p_phys.output_table != p_disp.output_table:
            raise ValueError(
                f"2NF cluster table mismatch: {p_phys.output_table!r} vs "
                f"{p_disp.output_table!r}"
            )
        phys_cols = p_phys.display_columns
        disp_cols = p_disp.display_columns
        if phys_cols != disp_cols:
            rename_map[p_phys.output_table] = list(zip(phys_cols, disp_cols))
            any_changed = True

    return rename_map if any_changed else None


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _build_pred_connection(
    db_path: str,
    col_rename_map: Dict[str, List[Tuple[str, str]]],
) -> sqlite3.Connection:
    """
    Open the physical SQLite DB and install TEMP VIEWs that shadow base tables
    with mapped column names (L3–L6 semantic renaming).
    """
    conn = sqlite3.connect(db_path)
    conn.text_factory = str
    if col_rename_map:
        for table, pairs in col_rename_map.items():
            select_parts = [
                f'main."{table}"."{orig_col}" AS `{mapped_col}`'
                for orig_col, mapped_col in pairs
            ]
            view_sql = (
                f'CREATE TEMP VIEW "{table}" AS '
                f'SELECT {", ".join(select_parts)} '
                f'FROM main."{table}"'
            )
            try:
                conn.execute(view_sql)
            except sqlite3.OperationalError as e:
                print(f"[evaluator] Warning: could not create TEMP VIEW for '{table}': {e}")
    return conn


def _execute(conn: sqlite3.Connection, sql: str, timeout_sec: float = _SQL_TIMEOUT_SEC) -> list:
    """Execute SQL and return all rows. Raises on error or timeout."""
    deadline = time.monotonic() + timeout_sec

    def _progress_handler() -> int:
        if time.monotonic() > deadline:
            return 1  # request interrupt
        return 0

    conn.set_progress_handler(_progress_handler, 10_000)
    try:
        cursor = conn.execute(sql)
        return cursor.fetchall()
    finally:
        conn.set_progress_handler(None, 0)


def _execute_safe(conn: sqlite3.Connection, sql: str):
    """
    Execute SQL without raising. Returns (rows, None) on success,
    (None, error_message) on failure.
    """
    try:
        rows = _execute(conn, sql)
        return rows, None
    except sqlite3.OperationalError as e:
        if "interrupted" in str(e).lower():
            return None, f"SQL execution timed out after {_SQL_TIMEOUT_SEC}s"
        return None, str(e)
    except Exception as e:
        return None, str(e)


def _result_sets_equal(pred_rows: list, gold_rows: list) -> bool:
    """
    Compare two result sets as multisets (Counter over normalised rows).
    Normalisation converts each value to a comparable string to avoid
    type mismatches between INTEGER 1 and REAL 1.0 representing the same value.
    """
    return Counter(_normalise(pred_rows)) == Counter(_normalise(gold_rows))


def _normalise(rows: list) -> list:
    """
    Convert each row to a tuple of normalised string values so that
    equivalent values with different Python types compare as equal.

    Examples:
      (1,)   and (1.0,)  → both become ('1',)    → equal
      (None,)            → ('',)
      ('YES',)           → ('yes',)               → case-insensitive
    """
    normalised = []
    for row in rows:
        norm_row = tuple(
            "" if v is None
            else str(float(v)).rstrip("0").rstrip(".") if _is_numeric(v)
            else str(v).strip().lower()
            for v in row
        )
        normalised.append(norm_row)
    return normalised


def _is_numeric(value) -> bool:
    """Return True if value is an int or float (not a string)."""
    return isinstance(value, (int, float)) and not isinstance(value, bool)


