#!/usr/bin/env python3
"""
Audit the S1/S2/S3 column-name mapping (src/column_aliases.py) for every
database used in the experiments.

Reports, per database and overall:
  1. Mapping coverage — each column falls into one of the reviewer's rows:
       A  S2 = original, S3 = new          (original already abbreviated; S3 expanded)
       B  S2 = new,      S3 = original     (original already descriptive; S2 abbreviated)
       C  S2 = new,      S3 = new          (original partly abbreviated; both generated)
       D  S2 = original, S3 = original     (fallback: no transformation at either level)
     plus whether a BIRD column_description exists and whether S3 matches the
     BIRD `column_name` expansion.
  2. Collision rates — duplicate names produced within one table (L3-L6), within
     the L1 wide table, and within each L2 cluster, for S1/S2/S3.
  3. Examples — one table per database with S1/S2/S3 side by side.

Usage (from schema_effect/):
    .venv/bin/python analysis/audit_semantic_mapping.py > docs/semantic_mapping_audit.md
"""
from __future__ import annotations

import csv
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from src.column_aliases import ALIASES, get_name  # noqa: E402

BIRD_DIR = _ROOT / "dev_20240627"
SPIDER_DIR = BIRD_DIR / "spider_data"
BIRD_DBS = ["california_schools", "debit_card_specializing", "european_football_2", "financial",
            "formula_1", "student_club", "superhero", "thrombosis_prediction", "toxicology"]
SPIDER_DBS = ["car_1", "tvshow"]


def norm(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_")


def load_tables(tables_json: Path) -> dict:
    out = {}
    for e in json.loads(tables_json.read_text()):
        tbls = e["table_names_original"]
        cols = defaultdict(list)
        for ti, cname in e["column_names_original"]:
            if ti < 0:
                continue
            cols[tbls[ti]].append(cname)
        out[e["db_id"]] = dict(cols)
    return out


def load_descriptions(db_id: str) -> dict:
    """{table: {orig_col: (column_name, column_description)}} from BIRD CSVs."""
    d = BIRD_DIR / "dev_databases" / db_id / "database_description"
    out = {}
    if not d.is_dir():
        return out
    for p in d.glob("*.csv"):
        rows = {}
        for enc in ("utf-8-sig", "latin-1"):
            try:
                with p.open(encoding=enc, newline="") as f:
                    for r in csv.DictReader(f):
                        oc = (r.get("original_column_name") or "").strip()
                        rows[oc] = ((r.get("column_name") or "").strip(),
                                    (r.get("column_description") or "").strip())
                break
            except UnicodeDecodeError:
                continue
        out[p.stem] = rows
    return out


def idx_to_label(i: int) -> str:
    s = ""
    i += 1
    while i:
        i, r = divmod(i - 1, 26)
        s = chr(97 + r) + s
    return s


def main() -> None:
    bird_tables = load_tables(BIRD_DIR / "dev_tables.json")
    spider_tables = load_tables(SPIDER_DIR / "tables.json")
    out = []
    P = out.append

    P("# Semantic-level mapping audit (S1 / S2 / S3)\n")
    P("Generated by `analysis/audit_semantic_mapping.py` from `src/column_aliases.py`, "
      "`dev_tables.json`, `spider_data/tables.json` and the BIRD `database_description` CSVs.\n")

    # ------------------------------------------------------------------ coverage
    P("## 1. Mapping coverage\n")
    P("Row definitions (per column, comparing the S2/S3 name to the original after normalising "
      "case/punctuation):\n")
    P("- **A** original abbreviated: S2 = original, S3 = new expansion")
    P("- **B** original descriptive: S2 = new abbreviation, S3 = original")
    P("- **C** original mixed: S2 = new abbreviation, S3 = new expansion")
    P("- **D** fallback: S2 = S3 = original (no transformation at either level)\n")
    P("| database | columns | A | B | C | D (fallback) | S2≠orig | S3≠orig | S2≠S3 | has BIRD desc | S3 = BIRD column_name |")
    P("|--|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|")
    tot = Counter()
    fallback_examples = defaultdict(list)
    all_rows = []
    for db_id, tables in [(d, bird_tables[d]) for d in BIRD_DBS] + [(d, spider_tables[d]) for d in SPIDER_DBS]:
        descs = load_descriptions(db_id)
        c = Counter()
        for t, cols in tables.items():
            for i, col in enumerate(cols):
                s2, s3 = get_name(db_id, col, 2), get_name(db_id, col, 3)
                n0, n2, n3 = norm(col), norm(s2), norm(s3)
                row = ("A" if n2 == n0 and n3 != n0 else
                       "B" if n2 != n0 and n3 == n0 else
                       "C" if n2 != n0 and n3 != n0 else "D")
                cn, cd = descs.get(t, {}).get(col, ("", ""))
                c["n"] += 1
                c[row] += 1
                c["s2diff"] += n2 != n0
                c["s3diff"] += n3 != n0
                c["s23diff"] += n2 != n3
                c["hasdesc"] += bool(cd)
                c["s3eqcn"] += bool(cn) and norm(cn) == n3
                if row == "D":
                    fallback_examples[db_id].append(col)
                all_rows.append((db_id, t, i, col, s2, s3, row))
        tot.update(c)
        n = c["n"]
        P(f"| {db_id} | {n} | {c['A']} ({100*c['A']/n:.0f}%) | {c['B']} ({100*c['B']/n:.0f}%) | "
          f"{c['C']} ({100*c['C']/n:.0f}%) | {c['D']} ({100*c['D']/n:.0f}%) | "
          f"{100*c['s2diff']/n:.0f}% | {100*c['s3diff']/n:.0f}% | {100*c['s23diff']/n:.0f}% | "
          f"{100*c['hasdesc']/n:.0f}% | {100*c['s3eqcn']/n:.0f}% |")
    n = tot["n"]
    P(f"| **all** | {n} | {tot['A']} ({100*tot['A']/n:.0f}%) | {tot['B']} ({100*tot['B']/n:.0f}%) | "
      f"{tot['C']} ({100*tot['C']/n:.0f}%) | {tot['D']} ({100*tot['D']/n:.0f}%) | "
      f"{100*tot['s2diff']/n:.0f}% | {100*tot['s3diff']/n:.0f}% | {100*tot['s23diff']/n:.0f}% | "
      f"{100*tot['hasdesc']/n:.0f}% | {100*tot['s3eqcn']/n:.0f}% |")
    P("\nFallback (row D) columns, i.e. identical at S2 and S3:\n")
    for db_id, cols in fallback_examples.items():
        P(f"- {db_id} ({len(cols)}): " + ", ".join(f"`{c}`" for c in cols))
    P("")

    # ------------------------------------------------------------------ collisions
    P("## 2. Collision check\n")
    P("A collision = two distinct original columns in the same table (L3-L6), in the L1 wide table, "
      "or in the same L2 cluster, that receive the same name at a given semantic level "
      "(case-insensitive).\n")
    P("| database | level | L3-L6 per-table collisions | L1 wide-table collisions | L2 per-cluster collisions | cross-table same-name (L3-L6, informational) |")
    P("|--|--|--:|--:|--:|--:|")
    coll_details = []
    from preprocess_data.to_1nf.convert import build_plan as plan1
    from preprocess_data.to_2nf.convert import build_plan as plan2
    for db_id, tables, data_dir, tj in (
        [(d, bird_tables[d], BIRD_DIR, BIRD_DIR / "dev_tables.json") for d in BIRD_DBS]
        + [(d, spider_tables[d], SPIDER_DIR, SPIDER_DIR / "tables.json") for d in SPIDER_DBS]
    ):
        for sem in (1, 2, 3):
            per_table = 0
            cross = 0
            names_by_table = {}
            for t, cols in tables.items():
                names = [f"col_{idx_to_label(i)}" if sem == 1 else get_name(db_id, c, sem).lower()
                         for i, c in enumerate(cols)]
                dup = {k: v for k, v in Counter(names).items() if v > 1}
                per_table += sum(v - 1 for v in dup.values())
                for k in dup:
                    coll_details.append((db_id, f"S{sem}", f"table {t}", k,
                                         [c for c, nm in zip(cols, names) if nm == k]))
                names_by_table[t] = set(names)
            if sem > 1:
                cnt = Counter(nm for s in names_by_table.values() for nm in s)
                cross = sum(1 for v in cnt.values() if v > 1)
            try:
                dc = [c.lower() for c in plan1(db_id, data_dir, semantic_level=sem, tables_path=tj).display_columns]
                l1 = sum(v - 1 for v in Counter(dc).values() if v > 1)
                for k, v in Counter(dc).items():
                    if v > 1:
                        coll_details.append((db_id, f"S{sem}", "L1 wide table", k, [f"x{v}"]))
            except Exception as e:  # pragma: no cover
                l1 = f"n/a ({type(e).__name__})"
            try:
                p2 = plan2(db_id, data_dir, semantic_level=sem, tables_path=tj)
                l2 = 0
                for cl in p2.clusters:
                    dc = [c.lower() for c in cl.display_columns]
                    l2 += sum(v - 1 for v in Counter(dc).values() if v > 1)
                    for k, v in Counter(dc).items():
                        if v > 1:
                            coll_details.append((db_id, f"S{sem}", f"L2 cluster {cl.output_table}", k, [f"x{v}"]))
            except Exception as e:  # pragma: no cover
                l2 = f"n/a ({type(e).__name__})"
            P(f"| {db_id} | S{sem} | {per_table} | {l1} | {l2} | {cross if sem > 1 else '—'} |")
    P("")
    if coll_details:
        P("Collision details:\n")
        for db_id, sem, where, name, srcs in coll_details:
            P(f"- {db_id} · {sem} · {where}: `{name}` ← {', '.join(f'`{s}`' for s in srcs)}")
    else:
        P("No collisions found at any level.")
    P("")

    # ------------------------------------------------------------------ examples
    P("## 3. Examples across databases (S1 / S2 / S3)\n")
    P("| database | table | original | S1 | S2 | S3 | row |")
    P("|--|--|--|--|--|--|--|")
    picked = defaultdict(int)
    for db_id, t, i, col, s2, s3, row in all_rows:
        key = (db_id, row)
        if picked[key] >= 1 or picked[(db_id, "n")] >= 4:
            continue
        picked[key] += 1
        picked[(db_id, "n")] += 1
        P(f"| {db_id} | {t} | `{col}` | `col_{idx_to_label(i)}` | `{s2}` | `{s3}` | {row} |")
    P("")

    print("\n".join(out))


if __name__ == "__main__":
    main()
